catalog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", index, name="index"),
    path('<int:category_id>/', category, name="category"),
    path('baket/add/<int:product_id>/', basket_add, name="basket_add"),
    path('basket/del/<int:product_id>/', basket_del, name="basket_del"),
    path('basket/minus/<int:product_id>', basket_quantity, name="basket_quantity"),
    path('<int:category_id>/<int:product_id>/', product_page, name="product_page"),
    path('basket', basket_page, name="basket_page"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("catalog.urls")),
    path('order/', include("orders.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

orders/urls.py
from django.urls import path
from .views import *


app_name = 'orders'

urlpatterns = [
    path("", MakeOrder, name="MakeOrder"),
    
]

catalog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=80, verbose_name='Название категории')
    description = models.CharField(max_length=200, verbose_name='Краткое описание')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=80, verbose_name='Название товара')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quntity = models.PositiveIntegerField(default=0)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='product_images/%Y-%m-%d/', verbose_name='Фотографии товара', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, related_name='attributes', db_index=True, verbose_name='Товар',
                                on_delete=models.CASCADE)
    attribute_name = models.CharField(max_length=80, verbose_name='Название характеристики')
    attribute_value = models.CharField(max_length=80, verbose_name='Значение характеристики')

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

    def __str__(self) -> str:
        return self.attribute_name

class Basket(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qauntity = models.PositiveSmallIntegerField(default=0)
    session = models.CharField(max_length=40, null=True)

    @classmethod
    def create_or_update(self, product_id, session):
        baskets = Basket.objects.filter(session=session, product_id=product_id)
        if baskets.exists():
            basket = baskets.first()
            basket.qauntity += 1
            basket.save()
        else:
            basket = Basket.objects.create(session=session, product_id=product_id, qauntity=1)

    @classmethod
    def basket_delete(self, session, product_id):
        basket = Basket.objects.get(session=session, product_id=product_id)
        basket.delete()

    @classmethod
    def edit_quantity(self, session, product_id):
        basket = Basket.objects.get(session=session, product_id=product_id)
        if basket.qauntity == 1:
            basket.delete()
        else:
            basket.qauntity = basket.qauntity - 1
            basket.save()


    @classmethod
    def total_sum(self, session):
        baskets = Basket.objects.filter(session=session)
        return sum([basket.sum() for basket in baskets])

    def sum(self):
        return self.qauntity * self.product.price

    def __str__(self):
        return f'Корзина для {self.session}'

    @classmethod
    def basket_to_json(self, session):
        baskets = Basket.objects.filter(session=session)
        return [{"id": basket.product.id,
                 "product_name": basket.product.name,
                 "quantity": basket.qauntity,
                 "sum": self.sum()} for basket in baskets]

orders/models.py
from django.db import models

# Create your models here.


class Order(models.Model):
    full_name = models.CharField(max_length=256)
    email = models.EmailField(max_length=256)
    # basket_history = models.JSONField()
    address = models.CharField(max_length=256)
    phone_number = models.CharField(max_length=50)
    

orders/forms.py
from django import forms
from .models import Order

class Orderform(forms.ModelForm):
    full_name = forms.CharField(label="ФИО", widget=forms.TextInput(attrs={'class': 'form-input', "placeholder": "Фамилия Имя Отчество"}))
    phone_number = forms.CharField(label="Телефон", widget=forms.TextInput(attrs={'class': 'form-input', "placeholder": "+ 7 999 999 99 99"}))
    email = forms.EmailField(max_length=256, label="E-mail", widget=forms.TextInput(attrs={'class': 'form-input', "placeholder": "Электронаая почта"}))
    address = forms.CharField(max_length=256, label="Адресс доставки", widget=forms.TextInput(attrs={'class': 'form-input', "placeholder": "Адресс доставки"}))
    
    
    class Meta:
        model = Order
        fields = ('full_name', 'phone_number', 'email', 'address')
        

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product, Category, Basket, ProductAttribute
from django.shortcuts import HttpResponseRedirect


def index(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request, "catalog/index.html", {"products": products, "categories": categories, })


def category(request, category_id):
    categories = Category.objects.all()
    products = Product.objects.filter(category_id=category_id)
    return render(request, "catalog/category.html", {"products": products, "categories": categories})


def basket_add(request, product_id):
    Basket.create_or_update(session=request.session.session_key, product_id=product_id)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_del(request, product_id):
    Basket.basket_delete(session=request.session.session_key, product_id=product_id)
    return HttpResponseRedirect("/home/basket")


def basket_quantity(request, product_id):
    Basket.edit_quantity(session=request.session.session_key, product_id=product_id)
    return HttpResponseRedirect('/home/basket')


def product_page(request, category_id, product_id):
    product = Product.objects.get(pk=product_id, category_id=category_id)
    info = ProductAttribute.objects.filter(product_id=product_id)
    return render(request=request, template_name="catalog/product.html", context={"product" : product, "info": info})


def basket_page(request):
    baskets = Basket.objects.filter(session=request.session.session_key).order_by('id')
    total_price = Basket.total_sum(session=request.session.session_key)
    return render(request=request, template_name="catalog/basket.html", context={"baskets" : baskets, "total_price": total_price})

orders/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import Orderform
# Create your views here.

def MakeOrder(request):
    if request.method == 'POST':
        form = Orderform(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/home")
    else:
        form = Orderform()
    return render(request, 'orders/order.html', {'form':form})

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VITAL MEBEL</title>
    <link rel="stylesheet" href="{% static 'catalog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'catalog/css/normalize.css' %}">
</head>
<body>
    <nav class="navbar">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 92 92" id="menu"><path d="M78 23.5H14c-3.6 0-6.5-2.9-6.5-6.5s2.9-6.5 6.5-6.5h64c3.6 0 6.5 2.9 6.5 6.5s-2.9 6.5-6.5 6.5zM84.5 46c0-3.6-2.9-6.5-6.5-6.5H14c-3.6 0-6.5 2.9-6.5 6.5s2.9 6.5 6.5 6.5h64c3.6 0 6.5-2.9 6.5-6.5zm0 29c0-3.6-2.9-6.5-6.5-6.5H14c-3.6 0-6.5 2.9-6.5 6.5s2.9 6.5 6.5 6.5h64c3.6 0 6.5-2.9 6.5-6.5z"></path></svg>
        <div class="logo">
            <a href="{% url 'index' %}">VITAL MEBEL</a>
        </div>
        <div class="container">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 24 24" id="cart"><path d="M8.5,19A1.5,1.5,0,1,0,10,20.5,1.5,1.5,0,0,0,8.5,19ZM19,16H7a1,1,0,0,1,0-2h8.49121A3.0132,3.0132,0,0,0,18.376,11.82422L19.96143,6.2749A1.00009,1.00009,0,0,0,19,5H6.73907A3.00666,3.00666,0,0,0,3.92139,3H3A1,1,0,0,0,3,5h.92139a1.00459,1.00459,0,0,1,.96142.7251l.15552.54474.00024.00506L6.6792,12.01709A3.00006,3.00006,0,0,0,7,18H19a1,1,0,0,0,0-2ZM17.67432,7l-1.2212,4.27441A1.00458,1.00458,0,0,1,15.49121,12H8.75439l-.25494-.89221L7.32642,7ZM16.5,19A1.5,1.5,0,1,0,18,20.5,1.5,1.5,0,0,0,16.5,19Z"></path></svg>
            </a>
            </div>
        
    </nav>
    <main>
        <img class="mainpage" src="{% static 'catalog/img/main.png' %}">
        <div class="hz"></div>
        <nav class="nav-cat">
            <div class="cat-container">
                <div class="navwrap">
                    <ul class="cats">
                        <li><a href="{% url 'index' %}">Все</a></li>
                        {% for category in categories %}
                        <li><a href="{% url 'category' category.id %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </nav>
        </div>
        {% block content %}    
        {% endblock %}
    </main>
</body>
</html>

catalog/templates/catalog/category.html
{% extends "catalog/base.html" %}
{% load humanize %}
{% load custom_filters %}

{% block content %}
<div class="cat-cards-container">
    <div class="cat-cards-container">
        <div class="cat-cards">
            {% for product in products %}
            <div class="cat-cards__card">
                <a class="cat-cards__link" href="{% url 'product_page' product.category.pk product.id %}">
                    <div class="image">
                    <img src="{{ product.images.url }}" alt="item">
                    </div>
                    <span class="cat-cards__card__name">{{ product.name }}</span>
                    <span class="cat-cards__card__price">{{ product.price|floatformat|intcomma|stringreplace}} ₽</span>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% load humanize %}
{% load custom_filters %}

{% block content %}
<div class="cat-cards-container">
    <div class="cat-cards-container">
        <div class="cat-cards">
            {% for product in products %}
            <div class="cat-cards__card">
                <a class="cat-cards__link" href="{% url 'product_page' product.category.pk product.id %}">
                    <div class="image">
                    <img src="{{ product.images.url }}" alt="item">
                    </div>
                    <span class="cat-cards__card__name">{{ product.name }}</span>
                    <span class="cat-cards__card__price">{{ product.price |floatformat|intcomma|stringreplace}}</span>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

catalog/templates/catalog/product.html
{% load static %}
{% load humanize %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VITAL MEBEL</title>
    <link rel="stylesheet" href="{% static 'catalog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'catalog/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'catalog/css/productpage.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 92 92" id="menu"><path d="M78 23.5H14c-3.6 0-6.5-2.9-6.5-6.5s2.9-6.5 6.5-6.5h64c3.6 0 6.5 2.9 6.5 6.5s-2.9 6.5-6.5 6.5zM84.5 46c0-3.6-2.9-6.5-6.5-6.5H14c-3.6 0-6.5 2.9-6.5 6.5s2.9 6.5 6.5 6.5h64c3.6 0 6.5-2.9 6.5-6.5zm0 29c0-3.6-2.9-6.5-6.5-6.5H14c-3.6 0-6.5 2.9-6.5 6.5s2.9 6.5 6.5 6.5h64c3.6 0 6.5-2.9 6.5-6.5z"></path></svg>
        <div class="logo">
            <a href="{% url 'index' %}">VITAL MEBEL</a>
        </div>
        <div class="container">
            <a href="{% url 'basket_page' %}">
                <svg xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 24 24" id="cart"><path d="M8.5,19A1.5,1.5,0,1,0,10,20.5,1.5,1.5,0,0,0,8.5,19ZM19,16H7a1,1,0,0,1,0-2h8.49121A3.0132,3.0132,0,0,0,18.376,11.82422L19.96143,6.2749A1.00009,1.00009,0,0,0,19,5H6.73907A3.00666,3.00666,0,0,0,3.92139,3H3A1,1,0,0,0,3,5h.92139a1.00459,1.00459,0,0,1,.96142.7251l.15552.54474.00024.00506L6.6792,12.01709A3.00006,3.00006,0,0,0,7,18H19a1,1,0,0,0,0-2ZM17.67432,7l-1.2212,4.27441A1.00458,1.00458,0,0,1,15.49121,12H8.75439l-.25494-.89221L7.32642,7ZM16.5,19A1.5,1.5,0,1,0,18,20.5,1.5,1.5,0,0,0,16.5,19Z"></path></svg>
            </a>
            </div>
        
    </nav>
    <main class="main-product-page">
        <div class="product-page">
            <div class="back-to-catalog">
                <svg width="17" height="9" viewBox="0 0 17 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M16 4.5L1 4.5M1 4.5L6.625 8M1 4.5L6.625 1" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                <a href="{% url 'index' %}">Вернуться в каталог</a>
            </div>
            <img class="product-img" src="{{ product.images.url }}">
            <div class="under-product">
                <div class="product-price">{{product.price|floatformat|intcomma|stringreplace}}</div>
                <div class="obertka">
                    <a href="{% url 'basket_add' product.id %}">
                        <button class="basket-button">В корзину</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="right-container">
            <div class="info-container">
                <section>"{{product.name}}"</section>
                <div class="characteristicks">Описание: {{product.description}}</div>
                <section>Характеристики</section>
                {% for item in info %}
                <div class="characteristicks values">{{item.attribute_name}}: {{item.attribute_value}}</div>
                {% endfor %}
            </div>
            
        </div>
    </main>
</body>
</html>

orders/templates/orders/order.html
{% load static %}
{% load humanize %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VITAL MEBEL</title>
    <link rel="stylesheet" href="{% static 'catalog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'catalog/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'orders/css/order.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 92 92" id="menu"><path d="M78 23.5H14c-3.6 0-6.5-2.9-6.5-6.5s2.9-6.5 6.5-6.5h64c3.6 0 6.5 2.9 6.5 6.5s-2.9 6.5-6.5 6.5zM84.5 46c0-3.6-2.9-6.5-6.5-6.5H14c-3.6 0-6.5 2.9-6.5 6.5s2.9 6.5 6.5 6.5h64c3.6 0 6.5-2.9 6.5-6.5zm0 29c0-3.6-2.9-6.5-6.5-6.5H14c-3.6 0-6.5 2.9-6.5 6.5s2.9 6.5 6.5 6.5h64c3.6 0 6.5-2.9 6.5-6.5z"></path></svg>
        <div class="logo">
            <a href="{% url 'index' %}">VITAL MEBEL</a>
        </div>
        <div class="container">
            <a href="{% url 'basket_page' %}">
                <svg xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 24 24" id="cart"><path d="M8.5,19A1.5,1.5,0,1,0,10,20.5,1.5,1.5,0,0,0,8.5,19ZM19,16H7a1,1,0,0,1,0-2h8.49121A3.0132,3.0132,0,0,0,18.376,11.82422L19.96143,6.2749A1.00009,1.00009,0,0,0,19,5H6.73907A3.00666,3.00666,0,0,0,3.92139,3H3A1,1,0,0,0,3,5h.92139a1.00459,1.00459,0,0,1,.96142.7251l.15552.54474.00024.00506L6.6792,12.01709A3.00006,3.00006,0,0,0,7,18H19a1,1,0,0,0,0-2ZM17.67432,7l-1.2212,4.27441A1.00458,1.00458,0,0,1,15.49121,12H8.75439l-.25494-.89221L7.32642,7ZM16.5,19A1.5,1.5,0,1,0,18,20.5,1.5,1.5,0,0,0,16.5,19Z"></path></svg>
            </a>
            </div>
        
    </nav>
    <main>
        <div class="contact-info">Контактные данные</div>
        <form action="{% url 'orders:MakeOrder' %}" method="post">
            {% csrf_token %}
            <div class="form-div">
                <label class="form-div-label" for="id_full_name">ФИО:</label>
                <input type="text" name="full_name" class="form-input" placeholder="Фамилия Имя Отчество" required="" id="id_full_name">
            </div>
            <div class="form-div">
                <label class="form-div-label" for="id_phone_number">Телефон:</label>
                <input type="text" name="phone_number" class="form-input" placeholder="+ 7 999 999 99 99" required="" id="id_phone_number">
            </div>
            <div class="form-div">  
                <label class="form-div-label" for="id_email">E-mail:</label>
                <input type="text" name="email" class="form-input" placeholder="Электронаая почта" maxlength="256" required="" id="id_email">
            </div>
            <div class="form-div">
                <label class="form-div-label" for="id_address">Адресс доставки:</label>
                <input style="box-sizing:content-box;" type="text" id="address" name="address" class="form-input"  placeholder="Адресс доставки" maxlength="256" required="" id="id_address">
                <script src="{% static 'orders/js/address.js' %}"></script>
                <script src="{% static 'orders/js/orders.js' %}"></script>
                <script>
                    $("#address").suggestions({
                        token: "832051e96688d68854774e8ddbdaf6b2b706e42a",
                        type: "ADDRESS",
                        /* Вызывается, когда пользователь выбирает одну из подсказок */
                        onSelect: function(suggestion) {
                            console.log(suggestion);
                        }
                    });
                </script>
            </div>
            <div class="but">
                <input class="but-input" type="submit" value="Продолжить">
            </div>
        </form>
    </main>
</body>
</html>